AWSTemplateFormatVersion: '2010-09-09'
Description: AWS Challenge IaC - Day 2 - Add Public Read Policy to Existing Bucket

Resources:
  S3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: awscloudformationiacchallenge-karlj-20250804
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal: '*'
            Action: 's3:GetObject'
            Resource: arn:aws:s3:::awscloudformationiacchallenge-karlj-20250804/*
