AWSTemplateFormatVersion: "2010-09-09"
Description: Day 26 - Create IAM User with programmatic access

Resources:
  MyIAMUser:
    Type: AWS::IAM::User
    Properties:
      UserName: day26-user
      Policies:
        - PolicyName: AllowS3Access
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: 
                  - s3:ListBucket
                  - s3:GetObject
                  - s3:PutObject
                Resource: "*"

  MyAccessKey:
    Type: AWS::IAM::AccessKey
    Properties:
      UserName: !Ref MyIAMUser

Outputs:
  AccessKeyId:
    Description: IAM Access Key ID
    Value: !Ref MyAccessKey
    Export:
      Name: Day26-AccessKeyId

  SecretAccessKey:
    Description: IAM Secret Access Key
    Value: !GetAtt MyAccessKey.SecretAccessKey
    Export:
      Name: Day26-SecretAccessKey
