AWSTemplateFormatVersion: '2010-09-09'
Description: Day 6 Challenge - IAM Role ith S3 Read/Write Access

Resources:
  Day6IAMRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: Day6S3AccessRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonS3FullAccess

Outputs:
  IAMRoleName:
    Value: !Ref Day6IAMRole
    Description: Name of the IAM Role Created