AWSTemplateFormatVersion: "2010-09-09"
Description: Day 25 - App Stack importing outputs

Resources:
  InstanceSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH and HTTP
      VpcId: !ImportValue VpcId-Export
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-0c02fb55956c7d316
      SecurityGroupIds:
        - !Ref InstanceSG
      SubnetId: !ImportValue SubnetId-Export
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          yum install -y httpd
          echo "<h1>Hello from Day 25 App Stack</h1>" > /var/www/html/index.html
          systemctl enable httpd
          systemctl start httpd
